### ISSUE TITLE
Improvement in docs and requirements.py

### ISSUE THREAD

**Issue by oliverbob** [geronimi73/phi2-finetune#1]
I came across a search about Phi2 finetuning. Could you please work on this repo? Provide some docs, because running your examples have plenty of errors.

I have to figure out by myself the missing pieces. 
Why not begin with a requirements.txt and then advice your followers to follow this tutorial on colab?

Will be working out the requirements.txt for you and I'll issue a PR when done.

Thanks.

**Comment by geronimi73** [comment]
OK. except for the requirements.txt, what else would you like to see?

**Comment by remember00000** [comment]
> OK. except for the requirements.txt, what else would you like to see?

Could you provide your inference codes?Thanks a lot for your valuable work.
I notice your inference codes as shown in your blog section 'Sample conversations with fine-tuned Phi-2' is not involved in this repo, sincenely hope this can be involed.

**Comment by oliverbob** [comment]
@geronimi73 I thought your code is for CPU, but when I tried it on colab, I couldn't make it to work. Could you please make a docs that's easy to follow that works on CPU? My GPU is not that capable.

If you don't mind, let's also create a Tinyllama enhancement as another repo for us to work on. Thanks. Kind of what ollama and ollama-webui has done to llama2.

Thanks.

**Comment by geronimi73** [comment]
> > OK. except for the requirements.txt, what else would you like to see?
> 
> Could you provide your inference codes?Thanks a lot for your valuable work. I notice your inference codes as shown in your blog section 'Sample conversations with fine-tuned Phi-2' is not involved in this repo, sincenely hope this can be involed.

@remember00000 you are right, that's missing. 

```python
question = "What is the meaning of life?"
messages = [
    {"role": "user", "content": question},
]
        
input_tokens = tokenizer.apply_chat_template(
    messages, 
    add_generation_prompt=True,
    return_tensors="pt"
).to("cuda")
output_tokens = model.generate(input_tokens, max_new_tokens=200)
output = tokenizer.decode(output_tokens[0])

print(output)
```

just uploaded an additional notebook https://github.com/geronimi73/phi2-finetune/blob/main/nb_inference.ipynb

**Comment by geronimi73** [comment]
> @geronimi73 I thought your code is for CPU, but when I tried it on colab, I couldn't make it to work. Could you please make a docs that's easy to follow that works on CPU? My GPU is not that capable.

sorry @oliverbob I just work with GPUs. If your GPU (or Colab) is not capable enough you might still be able to train by lowering ```max_length```. This will cut the samples and save VRAM. Depending on how long and complex the conversations you train on are, 512 tokens might still give good results. There's a notebook in the repo showing how to train on a free Colab instance: https://github.com/geronimi73/phi2-finetune/blob/main/nb_qlora_colab.ipynb 

> If you don't mind, let's also create a Tinyllama enhancement as another repo for us to work on. 

Not sure what you mean by "enhancement" but if you are referring to a minimal example on how to train TinyLlama, here is one: https://github.com/geronimi73/TinyLlama-versus-StableLM2/blob/main/nb_finetune_TinyLlama_OA2.ipynb

**Comment by oliverbob** [comment]
> > If you don't mind, let's also create a Tinyllama enhancement as another repo for us to work on.
> 
> Not sure what you mean by "enhancement" but if you are referring to a minimal example on how to train TinyLlama, here is one: https://github.com/geronimi73/TinyLlama-versus-StableLM2/blob/main/nb_finetune_TinyLlama_OA2.ipynb

Sorry about the confusion about "enhancement." I mean finetuning, especially making use of its "function calling" mechanism. Thanks for the link.
