### ISSUE TITLE
How to run training with Multiple GPU Setting? Giving Error while using QLora (runs with LoRA)

### ISSUE THREAD

**Issue by deshwalmahesh** [geronimi73/phi2-finetune#3]
Hey, I had faced the same issues for Flash Attention-2 saying something about `index_axis` so dropped it. But I'm facing one issue where it says that Model has been loaded in 8bit in different machine. I tried running my code with `torchrun ....` along with `Trainer` on 4xA10.  I was wondering if you faced the same issue.

Secondly, it's weird that once the training runs for 100 steps, evaluates and then it goes OOM. I'm using Batch of 2 per machine with 2048 length. Any idea? 

Also, even though you said that it's Multi GPU ready but how do I start training? Any special instructions like Lewis in [his script](https://gist.github.com/lewtun/b9d46e00292d9ecdd6fd9628d53c2814) says to run it with `trl` repo with Deep Speed.

**Comment by geronimi73** [comment]
> Also, even though you said that it's Multi GPU ready but how do I start training?

The code in `qlora.py` works as it is on a 24 GB GPU. You should be able to take that file without modifications and launch a QLoRA of phi-2 it with `accelerate launch qlora.py` on a 4xA10 machine. Regarding FA2, this [is still not fixed](https://github.com/huggingface/transformers/issues/28488), don't use it, make sure to **not** load the model with `attn_implementation="flash_attention_2"`.

> Hey, I had faced the same issues for Flash Attention-2 saying something about `index_axis` so dropped it.

Not sure what you are referring here, I haven't come across this index_axis dropped error.

**Comment by deshwalmahesh** [comment]
Thanks @geronimi73. `accelerate launch qlora.py` would use which of the approaches out of `FSDP, ZERO[1,2,3], DDP`? Or is it just based on the `accelerate config`? I ran it with DeepSpeed someone pointed out in `axolotl` that FSDP is having issues for now. 

I was wondering if FSDP would do better than ZERO-2? I am able to fit the model with `8_bit_adam` + `BF16` + 'tf32` (no use with BF16`) + Grad Checkpoint + Grad accumulation + LoRA (not QLoRA as it started giving error with `torchrun`)

**Comment by geronimi73** [comment]
yes, how it runs depends on how you set it up. I work with relatively small models that fit on each GPU and use DDP only.
